### ISSUE TITLE
The abbot-0.3.3.jar seems to be missing from downloads. Has it moved?

### ISSUE THREAD

**Issue by bzillig1** [CDRH/abbot#6]
The abbot-0.3.3.jar seems to be missing from downloads. Has it moved?

**Comment by sramsay** [comment]
On 30 January 2012 at 9:49, bzillig1 reply@reply.github.comwrote:

> The abbot-0.3.3.jar seems to be missing from downloads. Has it moved?

I suspect that was a GitHub bug (they had some trouble over the weekened, and they've been shifting things around).

I just re-uploaded it, so give it another try.

Steve

## 

Stephen Ramsay
Associate Professor
Department of English
Center for Digital Research in the Humanities
University of Nebraska-Lincoln
PGP Public Key ID: 0xA38D7B11
http://lenz.unl.edu/

**Comment by sramsay** [comment]
And . . . uploaded the wrong jar.  Should be fixed.
